### ISSUE TITLE
what will these routes suppose to do in business

### ISSUE THREAD

**Issue by pengw00** [findeasily/findeasily.net#111]
This is webside to help people to find rental houses easily, so I think there will be houses, apartments...,  people are more likely to search for 1b1b, studio, 2b2b, one, two or three bedroom. I thought it should be based on the property catageries. 

<img width="430" alt="cata" src="https://user-images.githubusercontent.com/6376970/62916827-a63bf200-bd5f-11e9-8ca7-4995dda52020.png">

**Comment by pengw00** [comment]
@zhouhao will  need to work on property services, the controller and ui?

**Comment by zhouhao** [comment]
This categories are not correct, I will update it soon.
I prefer: sub-lease, temp, long-term for categories now. Please feel free to let me know if you have any ideas for this?

**Comment by zhouhao** [comment]
The proposed categories can be:
* sub-lease
* temp
* long-term
* houses
* apartments
* more ...

Feel free to add new categories in your comments.
I will do some investigation from existing websites.

**Comment by pengw00** [comment]
I want to work on the categories, we can make it just like that for now.

**Comment by zhouhao** [comment]
Thank you! 
We can use either hardcoded static categories or database based categories(we can add new categories dynamically). We can start with static ones, as it is easier.

You can start from here: https://github.com/findeasily/findeasily.net/blob/master/src/main/resources/templates/layout/header.ftl#L13

**Comment by zhouhao** [comment]
FYI: You do not need to make it a perfect list at once, you can improve it with multiple pull requests.

**Comment by pengw00** [comment]
OK?That would be perfect?thanks man.

On Tue, Aug 13, 2019 at 1:08 AM SaltyEgg <notifications@github.com> wrote:

FYI: You do not need to make it a perfect list at once, you can improve it with multiple pull requests.

?

**Comment by pengw00** [comment]
OK, cool, that woud be perfect, thanks man.

**Comment by zhouhao** [comment]
Should thank you!
