### ISSUE TITLE
Auto reload tool without restarting server for developer happiness

### ISSUE THREAD

**Issue by pengw00** [findeasily/findeasily.net#119]
Right now when we have changes,  we have to restart the server to pick up the changes, if we could use some development tool for auto reloading server and web page.
[A recommand tool](https://dzone.com/articles/spring-boot-developer-tools-and-live-reload)

**Comment by zhouhao** [comment]
Thank you! :+1: 

BTW: we already have devtool integrated, but for Intellij, you have to press `ctrl+F9`(I remember, maybe wrong) to rebuild the project.
1. If it is not Java code change, e.g. css, html, freemarker, etc, you can refresh the page, and you can see the update immediately
2. If it is Java code change, it will restart the server automatically.

Previously, there is a tool called `JRebel`, which is very help for Java code change(no restart required), but the free version is not available anymore: https://my.jrebel.com/. And the paid one is very expensive.

**Comment by zhouhao** [comment]
You have a very good engineer-sense, and this is a very engineer-friendly feature.

**Comment by pengw00** [comment]
I use VScode, I should use Intellij instead.

**Comment by zhouhao** [comment]
Yes, I am sure Intellij is much better for this project
