### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by pengw00** [findeasily/findeasily.net#86]
When I run the commend, I got the problem like, it is something wrong happened in pom.xml?
I am new to Spring. I try to replace the dependency of springboot, but it doesn't work.
```
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fileService': Invocation of init method failed; nested exception is java.lang.Error: Unresolved compilation problems:
        The method getPath() is undefined for the type FileService.Folder
        log cannot be resolved

        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) ~[spring-beans-5.1.7.RELEASE.jar:5.1.7.RELEASE]
```

**Comment by zhouhao** [comment]
Hello, thank you for your issue.
I think it may be lombok related.
Can you please help to have a try with this: https://projectlombok.org/setup/intellij?

**Comment by pengw00** [comment]
I try the way you mentioned above, but still the same error, I am using Intellj, do you have any other idea?

**Comment by zhouhao** [comment]
Can you run this command below:
```bash
./mvnw clean package -DskipTests
```
If you can succeed it, maybe you should enable `annotation processing` in intellij:
![image](https://user-images.githubusercontent.com/2281521/62438183-1c56ae00-b6fb-11e9-8469-72f0e47bd72f.png)

**Comment by pengw00** [comment]
It can build successfully, but when run the commend, the error still there.
1)<img width="1068" alt="build-spring-success" src="https://user-images.githubusercontent.com/6376970/62439749-aa8a5e80-b712-11e9-8b3d-cdc7bebeffa4.png">
2)
<img width="1152" alt="error-fly-easily" src="https://user-images.githubusercontent.com/6376970/62439769-b9711100-b712-11e9-9f1b-8e5da66f6cbb.png">

**Comment by pengw00** [comment]
<img width="1059" alt="downloaded_lombok" src="https://user-images.githubusercontent.com/6376970/62440520-2e921580-b716-11e9-9033-5298856ae4fc.png">

**Comment by zhouhao** [comment]
Sorry it is my bad, I should have it documented somewhere.
You'd run this:
```bash
sudo mkdir -p /var/findeasily/resources
sudo chmod 777 /var/findeasily/resources
```
That fold is required to upload pictures.
If you want to configure it to another location, you can overwrite it here: https://github.com/findeasily/findeasily.net/blob/master/src/main/resources/application.properties#L34

Thank you

**Comment by pengw00** [comment]
Thanks man, that works.

**Comment by zhouhao** [comment]
np, have fun.

**Comment by pengw00** [comment]
Hey, bro, do you mind to reorg this project with reactJS, cauz I really like this project with springboot just like how I hate the UI here, never mind, I think it will be funny to repalce with reactJS.

**Comment by zhouhao** [comment]
I am sorry, I am not good at UI, so I bought the UI from [themeforest](https://themeforest.net/item/citybook-directory-listing-template/21360333) website.
And this theme is in raw html format.
Maybe in the future, I can rewrite it with React, but for now, I do not have any plan for that yet.

**Comment by pengw00** [comment]
> I am sorry, I am not good at UI, so I bought the UI from [themeforest](https://themeforest.net/item/citybook-directory-listing-template/21360333) website.
> And this theme is in raw html format.
> Maybe in the future, I can rewrite it with React, but for now, I do not have any plan for that yet.

Cool

**Comment by zhouhao** [comment]
If you can have a try, that will be great!
